name: "Deploy Lambda Function"

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로 실행
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # 배포할 리전

      # 배포 패키지 압축
      - name: Zip Lambda function
        run: zip -r lambda_test.zip lambda_test.js

      # Lambda 함수 배포
      - name: Deploy to AWS Lambda (Create if not exists)
        run: |
          FUNCTION_NAME="my-lambda-function-name"
          if aws lambda get-function --function-name $FUNCTION_NAME --region us-east-1; then
            echo "Function exists. Updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://lambda_test.zip
          else
            echo "Function not found. Creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::376129852049:role/my-lambda-execution-role \
              --handler lambda_test.handler \
              --zip-file fileb://lambda_test.zip \
              --region us-east-1
          fi
